### ISSUE TITLE
Stream overloads should be friend functions

### ISSUE THREAD

**Issue by oraqlle** [DimitrisGahtidis/dual_numbers#2]
The output stream operators (`<<`) should be a friend function. This means it can access the internals of your type by be treated as a free function ie. still take two parameters where one is **not** the `this` pointer of the enclosing class. This requires just moving its definition into the body of the class and using the `friend` qualifier.

## Example

This:

```cxx
    template<typename base_real_type>
    constexpr auto
    operator<<(std::ostream& os, dual<base_real_type> v)
        -> std::ostream&
    {
        os << v.re() << " + " << v.d() << "_eps";
        return os;
    }
```

would become this:

```cxx
    /// `dual` definition...
                                                            //< Removed template as it is just this instantiation of dual<T> type
    constexpr auto
    operator<<(std::ostream& os, const dual& v)    //< dual should also be const-ref as we do not modify it.
        -> std::ostream&
    {
        os << m_re << " + " << m_d << "_eps";    //< can now access internals, not a big deal for this class by good to know.
        return os;
    }

    /// rest of `dual` definition...
```

**Comment by DimitrisGahtidis** [comment]
I see, is this just a standard? Or is it following the methodology that "since `dual` is meant to be a 'type' (a class really but a type in design) in it's own respect the ostream overload should be contained inside the class itself" or something similar.

**Comment by oraqlle** [comment]
Both. It isn't enforced but is a best practice. The reason is because for operators on types, classes or structs where the left argument is the class type it is best to encapsulate the operator overload into the class as you can then remove the need to specify it in the parameter list because it is implicitly passed for any member function including operators. This can simplify functions, especially when templates get involved. The `<<` is no different except that in the context of iostreams it will always be the right argument but you still might want to uphold the semantics your type has with its operators. Also because `<<` is often used for string serialization, you might want to access the internal data to this function and just this function. Making it friend means it still is part of the classes interface but is truly a free function (doesn't belong to an object).

**Comment by DimitrisGahtidis** [comment]
That makes sense, changes are all done now.
